-- MySQL Script generated by MySQL Workbench
-- Wed Sep  8 00:55:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema u_calle
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u_calle` ;

-- -----------------------------------------------------
-- Schema u_calle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u_calle` ;
USE `u_calle` ;

-- -----------------------------------------------------
-- Table `u_calle`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Persona` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Persona` (
  `id_persona` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `fech_nac` DATE NULL,
  `genero` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NULL,
  `celular` BIGINT NOT NULL,
  `nacionalidad` VARCHAR(50) NULL,
  `nom_usuario` VARCHAR(15) NOT NULL,
  `contrasena` VARCHAR(40) NOT NULL,
  `creado_en` DATE NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Administrador` (
  `id_adm` INT NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_adm`, `id_persona`),
  INDEX `fk_Administrador_Persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_Administrador_Persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `u_calle`.`Persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Profesor` (
  `id_profesor` INT NOT NULL,
  `profesion` VARCHAR(45) NOT NULL,
  `id_persona` INT NOT NULL,
  `id_adm` INT NOT NULL,
  PRIMARY KEY (`id_profesor`, `id_persona`, `id_adm`),
  INDEX `fk_Profesor_Persona1_idx` (`id_persona` ASC) ,
  INDEX `fk_Profesor_Administrador1_idx` (`id_adm` ASC) ,
  CONSTRAINT `fk_Profesor_Persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `u_calle`.`Persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_Administrador1`
    FOREIGN KEY (`id_adm`)
    REFERENCES `u_calle`.`Administrador` (`id_adm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Programa_Academico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Programa_Academico` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Programa_Academico` (
  `id_progr` INT NOT NULL,
  `nom_progr` VARCHAR(70) NOT NULL,
  `abrv_progr` VARCHAR(3) NOT NULL,
  `jornada` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_progr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Estudiante` (
  `id_estudiante` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `id_progr` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`, `id_persona`, `id_progr`),
  INDEX `fk_Estudiante_Persona1_idx` (`id_persona` ASC) ,
  INDEX `fk_Estudiante_Programa_Academico1_idx` (`id_progr` ASC) ,
  CONSTRAINT `fk_Estudiante_Persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `u_calle`.`Persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Programa_Academico1`
    FOREIGN KEY (`id_progr`)
    REFERENCES `u_calle`.`Programa_Academico` (`id_progr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Asignatura` (
  `id_asign` INT NOT NULL,
  `nom_asign` VARCHAR(45) NOT NULL,
  `id_profesor` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `id_progr` INT NOT NULL,
  PRIMARY KEY (`id_asign`, `id_profesor`, `id_persona`, `id_progr`),
  INDEX `fk_Asignatura_Profesor1_idx` (`id_profesor` ASC, `id_persona` ASC),
  INDEX `fk_Asignatura_Programa_Academico1_idx` (`id_progr` ASC) ,
  CONSTRAINT `fk_Asignatura_Profesor1`
    FOREIGN KEY (`id_profesor` , `id_persona`)
    REFERENCES `u_calle`.`Profesor` (`id_profesor` , `id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_Programa_Academico1`
    FOREIGN KEY (`id_progr`)
    REFERENCES `u_calle`.`Programa_Academico` (`id_progr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Nota` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Nota` (
  `id_nota` INT NOT NULL,
  `calificacion` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id_nota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Coloca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Coloca` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Coloca` (
  `id_nota` INT NOT NULL,
  `id_profesor` INT NOT NULL,
  PRIMARY KEY (`id_nota`, `id_profesor`),
  INDEX `fk_Nota_has_Profesor_Profesor1_idx` (`id_profesor` ASC) ,
  INDEX `fk_Nota_has_Profesor_Nota1_idx` (`id_nota` ASC) ,
  CONSTRAINT `fk_Nota_has_Profesor_Nota1`
    FOREIGN KEY (`id_nota`)
    REFERENCES `u_calle`.`Nota` (`id_nota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota_has_Profesor_Profesor1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `u_calle`.`Profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Cursa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Cursa` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Cursa` (
  `id_estudiante` INT NOT NULL,
  `id_asign` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`, `id_asign`),
  INDEX `fk_Estudiante_has_Asignatura_Asignatura1_idx` (`id_asign` ASC) ,
  INDEX `fk_Estudiante_has_Asignatura_Estudiante1_idx` (`id_estudiante` ASC) ,
  CONSTRAINT `fk_Estudiante_has_Asignatura_Estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `u_calle`.`Estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Asignatura_Asignatura1`
    FOREIGN KEY (`id_asign`)
    REFERENCES `u_calle`.`Asignatura` (`id_asign`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u_calle`.`Tiene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u_calle`.`Tiene` ;

CREATE TABLE IF NOT EXISTS `u_calle`.`Tiene` (
  `id_asign` INT NOT NULL,
  `id_nota` INT NOT NULL,
  `id_estudiante` INT NOT NULL,
  PRIMARY KEY (`id_asign`, `id_nota`, `id_estudiante`),
  INDEX `fk_Asignatura_has_Nota_Nota1_idx` (`id_nota` ASC) ,
  INDEX `fk_Asignatura_has_Nota_Asignatura1_idx` (`id_asign` ASC) ,
  INDEX `fk_Asignatura_has_Nota_Estudiante1_idx` (`id_estudiante` ASC) ,
  CONSTRAINT `fk_Asignatura_has_Nota_Asignatura1`
    FOREIGN KEY (`id_asign`)
    REFERENCES `u_calle`.`Asignatura` (`id_asign`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_has_Nota_Nota1`
    FOREIGN KEY (`id_nota`)
    REFERENCES `u_calle`.`Nota` (`id_nota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_has_Nota_Estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `u_calle`.`Estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
